/* js/app/ui-helpers.js — Ajudantes de interface (cartões, mensagens) e modal de resultados. */
// ═══════════════════════════════════════════════════════════
//  RENDER CARD / UI HELPERS
// ═══════════════════════════════════════════════════════════
function renderAnswerCard(caminho, comoFazer, dicas, li, ehFixa = false) { const s = document.getElementById('chatStream'); const c = document.createElement('div'); c.className = 'answer-card'; c._dadosResposta = { caminho, como_fazer: comoFazer, dicas }; let h = ''; if (caminho && caminho !== 'null' && caminho.trim() !== '') { const p = caminho.split('>').map(p => p.trim()); const b = p.map((p, i) => i < p.length - 1 ? `<span>${p}</span><span class="sep">›</span>` : `<strong>${p}</strong>`).join(''); h += `<div class="answer-section"><div class="section-label path"><div class="section-icon path">🗺️</div>Caminho</div><div class="path-breadcrumb">${b}</div></div>`; } if (comoFazer) h += `<div class="answer-section"><div class="section-label how"><div class="section-icon how">✅</div>Como Fazer</div><div class="section-content">${comoFazer}</div></div>`; if (dicas && dicas.length > 0) { const dh = dicas.map(d => `<div class="tip-item"><span>💡</span><span>${d.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')}</span></div>`).join(''); h += `<div class="answer-section"><div class="section-label tip"><div class="section-icon tip">💡</div>Dicas</div>${dh}</div>`; } h += `<div class="feedback-area"><span>${ehFixa ? 'Continua útil?' : 'Ajudou?'}</span><button class="feedback-btn" onclick="saveFeedback(${li},'positivo',this)">👍</button><button class="feedback-btn" onclick="saveFeedback(${li},'negativo',this)">👎</button></div>`; c.innerHTML = h; s.appendChild(c); scrollToBottom(true); setTimeout(() => scrollToBottom(true), 50); return c; }
function appendLoadingCard(texto = "🔍 Buscando...") { const s = document.getElementById('chatStream'); const d = document.createElement('div'); d.className = 'message ai-msg'; d.style.cssText = 'display:flex;align-items:center;gap:10px;'; d.innerHTML = `<span>${texto}</span><span class="loading-dots"><span></span><span></span><span></span></span>`; s.appendChild(d); scrollToBottom(true); return d; }
function appendMessage(sender, text) { const s = document.getElementById('chatStream'); const d = document.createElement('div'); if (sender === 'ml') d.className = 'message ml-msg'; else d.className = sender === 'system' ? 'message system-msg' : `message ${sender === 'user' ? 'user-msg' : 'ai-msg'}`; d.innerHTML = text; s.appendChild(d); scrollToBottom(true); return d; }
function fillAndSend(txt) { document.getElementById('searchInput').value = txt; handleChat(); }


function openModal() { const b = document.getElementById('modalBody'); b.innerHTML = currentResults.map(r => `<div class="result-item"><strong>${(r.similaridade * 100).toFixed(0)}%</strong><br>${r.erro}<br>→ ${r.solucao}</div>`).join('') || '<em>Nenhum resultado.</em>'; document.getElementById('resultsModal').style.display = "block"; }
function closeModal() { document.getElementById('resultsModal').style.display = "none"; }
